package SacDaq::Web::Model::SensDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'SensDB',
    
    
);

=head1 NAME

SacDaq::Web::Model::SensDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SacDaq::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SensDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Stephen Cavilia

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
